"""create issues_blockers table

Revision ID: 97a12e8d9524
Revises: ade80b05915b
Create Date: 2024-04-06 18:11:45.777277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a12e8d9524'
down_revision: Union[str, None] = 'ade80b05915b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_blockers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocked_issue_id', sa.Integer(), nullable=False),
    sa.Column('blocking_issue_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocking_issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_blockers')
    # ### end Alembic commands ###
