"""create issues_relationships table

Revision ID: ade80b05915b
Revises: 064c1adaba40
Create Date: 2024-04-06 18:11:25.430234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade80b05915b'
down_revision: Union[str, None] = '064c1adaba40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_issue_id', sa.Integer(), nullable=False),
    sa.Column('child_issue_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue_relationships')
    # ### end Alembic commands ###
